name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd .github/workflows/cifuzz/
        docker build . --file Dockerfile -t build-fuzzers
        docker run --rm -v $(pwd)/fuzzers:/out -e FUZZING_LANGUAGE="c++" -t build-fuzzers
    - uses: actions/upload-artifact@v3
      with:
        name: fuzzers
        path: .github/workflows/cifuzz/fuzzers
